name: mywarranties
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^6.3.0

  firebase_core: ^3.13.0
  flutter_signin_button: ^2.0.0
  firebase_auth: ^5.5.2
  firebase_database: ^11.3.5

  shared_preferences: ^2.5.3

  cloud_firestore: ^5.6.6

  email_validator: ^3.0.0

  cloud_functions: ^5.4.0

  google_fonts: ^6.2.1

  image_picker: ^1.1.2
  file_picker: ^10.1.2
  firebase_storage: ^12.4.5
  url_launcher: ^6.3.1
  firebase_messaging: ^15.2.5
  flutter_local_notifications: ^16.3.0
  timezone: ^0.9.2
  workmanager: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/AppLogo.png
    - assets/google_logo.png