name: mywarranties
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^6.1.0

  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  flutter_signin_button: ^2.0.0

  cloud_firestore: ^5.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/AppLogo.png
    - assets/google_logo.png