name: mywarranties
description: "A Flutter project for managing warranties and receipts."
publish_to: 'none'
version: 0.43.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^6.2.1
  firebase_core: ^3.13.0
  flutter_signin_button: ^2.0.0
  firebase_auth: ^5.5.3
  firebase_database: ^11.3.5
  shared_preferences: ^2.5.3
  cloud_firestore: ^5.6.7
  email_validator: ^3.0.0
  cloud_functions: ^5.5.0
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  file_picker: ^10.1.9
  firebase_storage: ^12.4.5
  url_launcher: ^6.3.1
  open_filex: ^4.4.0
  firebase_messaging: ^15.2.5
  timezone: ^0.10.1
  flutter_background_service: ^5.0.5
  flutter_background_service_android: ^6.2.2
  intl: ^0.20.2
  uuid: ^4.3.3
  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  path_provider: ^2.1.1
  path: ^1.8.3
  awesome_notifications: ^0.10.1
  connectivity_plus: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/AppLogo.png
    - assets/google_logo.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/AppLogo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/AppLogo.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/AppLogo.png"
    background_color: "#FFFFFF"
    theme_color: "#0175C2"
  windows:
    generate: true
    image_path: "assets/AppLogo.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/AppLogo.png"